apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: udagram
type: Opaque
data:
  credentials: YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBWkZSMzVHUjNBQ0hCNVM0TQphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSBHQWhDdnhnM1F4Z09OVnV4K1NXRE82b0NhU2dpdllpc0loYUVJS1FB