apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  namespace: udagram
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
        - image: lupate01/udagram-reverseproxy:v1
          name: udagram-reverseproxy
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy-service
  namespace: udagram
  labels:
    app: udagram-reverseproxy
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: udagram-reverseproxy