language: node_js
node_js:
  - 12

services:
  - docker

install: []

before_script:
  - docker pull "beevelop/ionic" || true
  - docker pull "nginx:alpine" || true

script:
  - docker --version
  - docker build -f udagram-api-feed/Dockerfile -t  lupate01/udagram-api-feed:latest udagram-api-feed
  - docker build -f udagram-api-user/Dockerfile -t  lupate01/udagram-api-user:latest udagram-api-user
  - docker build -f udagram-frontend/Dockerfile -t  lupate01/udagram-frontend:latest udagram-frontend
  - docker build -f udagram-reverseproxy/Dockerfile -t  lupate01/reverseproxy:latest reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lupate01/udagram-api-feed:latest
  - docker push lupate01/udagram-api-user:latest
  - docker push lupate01/udagram-frontend:latest
  - docker push lupate01/reverseproxy:latest